### ISSUE TITLE
Swtching from phat-beat to internal audio and vice versa

### ISSUE THREAD

**Issue by gbrault** [pimoroni/phat-beat#16]
I would like to re enable PI internal audio and switch back an forth to phat beat: how could I do that? THX

**Comment by Gadgetoid** [comment]
If you have both `dtparam=audio=on` and `dtoverlay=hifiberry-dac` in your `/boot/config.txt` file then it should be possible to right-click on the speaker icon on the far right of the Raspbian Desktop task bar and choose between Analog (3.5mm jack), HDMI (HDMI output) and snd_rpi_hifiberry_dac (pHAT BEAT).
