### ISSUE TITLE
The VLC Radio installer does not work on this version of Raspbian...

### ISSUE THREAD

**Issue by PaulComis** [pimoroni/phat-beat#25]
Installing PirateRadio (get.pimoroni.com/vlcradio) on a new Pirate Radio Kit...

Install mostly works, but ends with:
<code>--- Warning ---

The VLC Radio installer

does not work on this version of Raspbian.

Check https://github.com//

</code>

Looks like the issue begins with the install of vnc-nox...
<code>
Checking for dependencies...

vlc-nox is required

Checking for dependencies...

vlc-nox is required

Installing vlc-nox...

E: Package 'vlc-nox' has no installation candidate

Apt failed to install vlc-nox!

Falling back on pypi...
</code>

This is in a new, clean install of raspian lite : 
<code>
uname -a

Linux raspberrypi 4.19.57+ #1244 Thu Jul 4 18:42:50 BST 2019 armv6l GNU/Linux

cat /etc/os-release

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"

NAME="Raspbian GNU/Linux"

VERSION_ID="10"

VERSION="10 (buster)"

VERSION_CODENAME=buster

...

</code>

Will continue to fiddle...

**Comment by PaulComis** [comment]
okay...fixed

looks like vlc-nox has been retired...

so in its place:
<code>
sudo apt-get install vlc-bin

sudo apt-get install vlc-plugin-base
</code>

then I re-ran the vlcradio install (curl https://get.pimoroni.com/vlcradio | bash) - although not entirely sure if this is necessary

Then created the files in a new ~/vlc directory, as outlined in [this gist](https://gist.github.com/Gadgetoid/47d8f873fde39fcbe83e6dab0e855f72)

and ran ~/vlc/setup.sh

and joy!

My next steps are to pick apart the radiovlc install, and propose a pull request...unless someone beats me to it (at the time of writing I'm a git noob)

**Comment by Gadgetoid** [comment]
Kindly submitted by @mstahel and merged - https://github.com/pimoroni/phat-beat/pull/26

Cheers all!
